# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffa7799e69bdc5a02e1417ce25e97866d780e5cd5c5db6ba45c145098b62ce38047f4993e827581dabd477b48418612f49c7a8c35a08dbc0440ccc61d66725b3

test:
  secret_key_base: 56a7e7ac01fe3da62cb0a5cbaf22ea3f4824ce424795951a90232a99f29c242fa06903fa5abdfdd95e4084f20129b4b6c69dfaf14b7564caa68efda198ce1b6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
